# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_pb2 as game__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGameMeta = channel.unary_unary(
                '/Game/GetGameMeta',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.GameMeta.FromString,
                _registered_method=True)
        self.SetGameMeta = channel.unary_unary(
                '/Game/SetGameMeta',
                request_serializer=game__pb2.GameMeta.SerializeToString,
                response_deserializer=game__pb2.Empty.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/Game/Reset',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.Empty.FromString,
                _registered_method=True)
        self.SuggestNextMove = channel.unary_unary(
                '/Game/SuggestNextMove',
                request_serializer=game__pb2.GameState.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)
        self.GetLastGameState = channel.unary_unary(
                '/Game/GetLastGameState',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)


class GameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGameMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGameMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestNextMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastGameState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGameMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameMeta,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.GameMeta.SerializeToString,
            ),
            'SetGameMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGameMeta,
                    request_deserializer=game__pb2.GameMeta.FromString,
                    response_serializer=game__pb2.Empty.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.Empty.SerializeToString,
            ),
            'SuggestNextMove': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestNextMove,
                    request_deserializer=game__pb2.GameState.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
            'GetLastGameState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastGameState,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Game', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGameMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Game/GetGameMeta',
            game__pb2.Empty.SerializeToString,
            game__pb2.GameMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGameMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Game/SetGameMeta',
            game__pb2.GameMeta.SerializeToString,
            game__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Game/Reset',
            game__pb2.Empty.SerializeToString,
            game__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestNextMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Game/SuggestNextMove',
            game__pb2.GameState.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLastGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Game/GetLastGameState',
            game__pb2.Empty.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
